# Generated by Django 5.1.1 on 2024-11-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='plan',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.TextField(),
        ),
    ]
